library(Rstox)
library(readr)
#' converts Rstoxreport of catch at age decomposed on gear, area and quarter,  to intercatch SD-lines
#' @param rstoxCatchAtAgeReport file generated by \code{\link[Rstox{saveDecomposedCatchMatrix}}
#' @param rstoxCatchMeanWeightReport file generated by \code{\link[Rstox{saveDecomposedAgeGroupParameters}}
#' @param outputfile file to write result to
#' @param gearmap list mapping gears to intercatch-fleet. SD-lines will only be generated for gears in gearmap
#' @param areaMap list mapping areas to ices areas
#' @param areaTypeMap list mapping areas to ices area types
#' @param species FAO code for species, e.g.: COD, HAD, POK
#' @param catchAtAgeUnit unit for catch at age, use "k" for thoushands, "m" for millions
convertToSdLines <- function(rstoxCatchAtAgeReport, rstoxCatchMeanWeightReport, outputfile, gearMap, areaMap, areaTypeMap, species, catchAtAgeUnit, year=2019, nationcode="NO", catchcategory="L", reportingcatorgy="R"){
  caa <- read_delim(rstoxCatchAtAgeReport, delim="\t", comment = "#")
  meanW <- read_delim(rstoxCatchMeanWeightReport, delim="\t", comment = "#")
  
  stopifnot(nrow(caa) == nrow(meanW))

  rap <- merge(caa,meanW, by=c("age", "gearfactor", "spatialGroup", "Quarter"), suffic=c(".caa", ".mw"))
    
  #
  # extract plusgroup and convert age to integer
  #
  
  plusgroupstring <- grep("\\+", rap$age, value=T)
  if (length(plusgroupstring)>0){
    plusgroup <- as.integer(unique(gsub("\\+", "", plusgroupstring)))
    stopifnot(length(plusgroup) == 1)
  }
  else{
    plusgroup <- -9
  }
  rap$age <- as.integer(gsub("\\+", "", rap$age))
  
  rap <- rap[rap$gearfactor %in% names(gearMap),]
  stopifnot(all(rap$spatialGroup %in% names(areaMap)))
  stopifnot(all(rap$spatialGroup %in% names(areaTypeMap)))
  
  stream <- file(outputfile, open="w")
  
  rap <- rap[order(rap$spatialGroup, rap$gearfactor, rap$Quarter, rap$age),]
  for (i in 1:nrow(rap)){
    age <- rap$age[i]
    quart <- substr(rap$Quarter[i], 2,2)
    fleet <- gearMap[[rap$gearfactor[i]]]
    area <- areaMap[[rap$spatialGroup[i]]]
    areatype <- areaTypeMap[[rap$spatialGroup[i]]]
    catchAtAge <- rap$mean[i]
    meanWeight <- rap$meanWeightG[i]/1000
    meanWeightUnit <- "kg"
    write(paste(c("SD", nationcode, year, "Quarter", quart, fleet, areatype, area, NA, species, NA, catchcategory, reportingcatorgy, "N", "Age", age, plusgroup,-9,-9,-9,-9,-9,meanWeightUnit,catchAtAgeUnit,"year",NA,NA, catchAtAge, meanWeight,-9,-9,-9,-9), collapse=","), stream)
  }
  
  close(stream)
}


#' makes Rstox-reports and converts to SD-lines
#' for each quarter
#' for fleets GNS_DEF_all_0_0_all (encoded as gearfactor Gillnet) and OTB_DEF_>=120_0_0_all (encoded as gearfactor Trawl)
#' for the areas covered by NSSK (2020 data call)
runProjectsAndMakeReportsGilnetTrawl <- function(projectname, species, SDlinesFilename, catchAtAgeReportFileName, meanWeightReportFileName){
  #
  # set units so they match, can be the same for all projects
  #
  unitReports = "thousands"
  unitInterCatch = "k"
  
  #
  # set up area and gear definitions so they match, can be the same for all projects
  #
  stoxReportArea <- list(a27.4=c("08","28", "40", "41", "42"), a27.3.a.20="09", a27.7.d="46", a27.6.a=c("43","47"))
  
  gearMap <- list()
  gearMap$Gillnet <- "GNS_DEF_all_0_0_all"
  gearMap$Trawl <- "OTB_DEF_>=120_0_0_all"
  
  areaMap <- list()
  areaTypeMap <- list()
  areaMap$a27.4 <- "27.4"
  areaTypeMap$a27.4 <- "SubArea"
  areaMap$a27.3.a.20 <- "27.3.a.20"
  areaTypeMap$a27.3.a.20 <- "SubDiv"
  areaMap$a27.7.d <- "27.7.d"
  areaTypeMap$a27.7.d <- "Div"
  areaMap$a27.6.a <- "27.6.a"
  areaTypeMap$a27.6.a <- "Div"
  
  #
  # Make Rstox reports
  #
  Rstox:::saveDecomposedCatchMatrix(stoxProjectname, catchAtAgeReportFileName, addQuarterToDecomp = T, plusgr=15, customMainAreaGrouping = stoxReportArea, decomposition = c("gearfactor"), unit = unitReports)
  Rstox:::saveDecomposedAgeGroupParameters(stoxProjectname, meanWeightReportFileName, addQuarterToDecomp = T, plusgr=15, customMainAreaGrouping = stoxReportArea, decomposition = c("gearfactor"))
  
  
  convertToSdLines(catchAtAgeReportFileName, meanWeightReportFileName, SDlinesFilename, gearMap, areaMap, areaTypeMap, speciesIntercatch, catchAtAgeUnit=unitInterCatch) 
  
}


#
# set species name and stox project, so they match
# must be configured for each project
#
stoxProjectname = "~/workspace/stox/ECA_prosjekter/NSSK/ECA_NSSK_torsk_2019/"
speciesIntercatch = "COD"


caaReport <- paste("caaReport_", speciesIntercatch, ".csv", sep="")
meanWeightReport <- paste("meanWeightReport_", speciesIntercatch, ".csv", sep="")
SDlines <- paste("SDLines_", speciesIntercatch, ".csv", sep="")
runProjectsAndMakeReportsGilnetTrawl(stoxProjectname, speciesIntercatch, SDlines, caaReport, meanWeightReport)
