library(Rstox)
library(readr)

get_quarter <- function(month){
  if (month %in% c("01", "02", "03")){
    return("1")
  }
  if (month %in% c("04", "05", "06")){
    return("2")
  }
  if (month %in% c("07", "08", "09")){
    return("3")
  }
  if (month %in% c("10", "11", "12")){
    return("4")
  }
}
get_quarter <- Vectorize(get_quarter)

#' converts Rstoxreport of catch at age decomposed on gear, area and quarter,  to intercatch SD-lines
#' @param rstoxCatchAtAgeReport file generated by \code{\link[Rstox{saveDecomposedCatchMatrix}}
#' @param rstoxCatchMeanWeightReport file generated by \code{\link[Rstox{saveDecomposedAgeGroupParameters}}
#' @param outputfile file to write result to
#' @param gearmap list mapping gears to intercatch-fleet. SD-lines will only be generated for gears in gearmap
#' @param areaMap list mapping areas to ices areas
#' @param areaTypeMap list mapping areas to ices area types
#' @param species FAO code for species, e.g.: COD, HAD, POK
#' @param catchAtAgeUnit unit for catch at age, use "k" for thoushands, "m" for millions
convertToSdLines <- function(rstoxCatchAtAgeReport, rstoxCatchMeanWeightReport, outputfile, gearMap, areaMap, areaTypeMap, species, catchAtAgeUnit, landings, year=2019, nationcode="NO", catchcategory="L", reportingcatorgy="R"){

  caa <- read_delim(rstoxCatchAtAgeReport, delim="\t", comment = "#")
  meanW <- read_delim(rstoxCatchMeanWeightReport, delim="\t", comment = "#")
  
  stopifnot(nrow(caa) == nrow(meanW))
  
  rap <- merge(caa,meanW, by=c("age", "metier", "spatialGroup", "quarter"), suffix=c(".caa", ".mw"))
    
  #
  # extract plusgroup and convert age to integer
  #
  
  plusgroupstring <- grep("\\+", rap$age, value=T)
  if (length(plusgroupstring)>0){
    plusgroup <- as.integer(unique(gsub("\\+", "", plusgroupstring)))
    stopifnot(length(plusgroup) == 1)
  }
  else{
    plusgroup <- -9
  }
  rap$age <- as.integer(gsub("\\+", "", rap$age))
  
  stopifnot(all(rap$spatialGroup %in% names(areaMap)))
  stopifnot(all(rap$spatialGroup %in% names(areaTypeMap)))
  
  stream <- file(outputfile, open="w")
  
  rap <- rap[order(rap$spatialGroup, rap$metier, rap$quarter, rap$age),]
  lastcell <- ""
  for (i in 1:nrow(rap)){
    
    quart <- rap$quarter[i]
    fleet <- rap$metier[i]
    area <- areaMap[[rap$spatialGroup[i]]]
    areatype <- areaTypeMap[[rap$spatialGroup[i]]]
  
    cell <- paste(quart, fleet, area)
    
    if (cell != lastcell){
      totalCatch <- sum(landings[landings$metier == fleet & landings$ICESarea == area & landings$quarter==quart,"rundvekt"])/1000
      
      # write HI line
      write(paste(c("HI", nationcode, year, "Quarter", quart, fleet, areatype, area, NA, NA, -9, NA), collapse=","), stream) 
      
      # write SI line
      write(paste(c("SI", nationcode, year, "Quarter", quart, fleet, areatype, area, NA, species, NA, catchcategory, reportingcatorgy, NA, NA, NA, NA,"T",totalCatch,-9,-9,"",""), collapse=","), stream) 
      lastcell <- cell      
    }
    
    # write SD lines
    if (rap$metier[i] %in% unlist(gearMap)){
      age <- rap$age[i]
      catchAtAge <- rap$mean[i]
      meanWeight <- rap$meanWeightG[i]/1000
      meanWeightUnit <- "kg"
      write(paste(c("SD", nationcode, year, "Quarter", quart, fleet, areatype, area, NA, species, NA, catchcategory, reportingcatorgy, "N", "Age", age, plusgroup,-9,-9,-9,-9,-9,meanWeightUnit,catchAtAgeUnit,"year",NA,NA, catchAtAge, meanWeight,-9,-9,-9,-9), collapse=","), stream) 
    }
  }
  
  close(stream)
}

stocks <- read.csv("data/stocks_COD_HAD_POK.csv", sep="\t", header = T, comment.char = "#", stringsAsFactors = F)
metier <- read.csv("data/fleet_COD_HAD_POK.csv", sep="\t", header=T, comment.char = "#", stringsAsFactors = F)
metierlandings <- read.csv("data/fleet_wo_logbook_COD_HAD_POK.csv", sep="\t", header=T, comment.char = "#", stringsAsFactors = F)
areas <- read.csv("data/areas_w47.csv", sep="\t", header = T, comment.char = "#", colClasses = c("character", "character", "character"), stringsAsFactors = F)

#puts metier on stox-landings
annotate_landings <- function(land){
  nr <- nrow(land)
  areas$FDIRarea <- as.integer(areas$FDIRarea)
  # annotate area on landings
  
  land <- merge(land, areas, all.x=T, by.x="hovedområdekode", by.y="FDIRarea")
  if (nrow(land)!=nr){
    stop("Too many rows after adding areas")
  }
  
  if (any(is.na(land$ICESarea))){
    print(unique(land[is.na(land$ICESarea),c("FDIRarea")]))
    stop("Some landings were not ICES area")
  }
  
  # annotate metier on landings
  land <- merge(land, metierlandings, all.x=T, by.x=c("redskapkode", "ICESarea", "ICESareatype"), by.y=c("REDSKAP_NS", "ICESarea", "ICESareatype"))
  if (nrow(land)!=nr){
    stop("Too many rows after adding metiers")
  }
  
  if (any(is.na(land$metier))){
    print(unique(land[is.na(land$metier),c("redskapkode", "ICESarea", "ICESareatype")]))
    stop("Some landings were not assigned metier")
  }
  
  land$quarter <- get_quarter(substr(land$sistefangstdato, 6,7))
  
  if (nrow(land)!=nr){
    stop("Too many rows")
  }
  return(land)
}

#' makes Rstox-reports and converts to SD-lines
#' for each quarter
#' for fleets GNS_DEF_all_0_0_all (encoded as gearfactor Gillnet) and OTB_DEF_>=120_0_0_all (encoded as gearfactor Trawl)
#' for the areas covered by NSSK (2020 data call)
runProjectsAndMakeReportsGilnetTrawl <- function(projectname, species, SDlinesFilename, catchAtAgeReportFileName, meanWeightReportFileName){
  
  #
  # annotate landings
  #
  
  l <- loadProjectData(projectname)
  land <- l$prepareRECA$StoxExport$landing
  land <- land[land$redskapkode != 90,] # ta vekk oppdrett
  
  if (!("metier" %in% names(land))){
    land <- annotate_landings(land)    
  }

  l$prepareRECA$StoxExport$landing <- land
  
  setProjectData(
    projectName = projectname,
    var = l$prepareRECA,
    name = "prepareRECA"
  )
  
  #
  # set units so they match, can be the same for all projects
  #
  unitReports = "thousands"
  unitInterCatch = "k"
  
  #
  # set up area and gear definitions so they match, can be the same for all projects
  #
  stoxReportArea <- list(a27.4=c("08","28", "40", "41", "42"), a27.3.a.20="09", a27.7.d="46", a27.6.a=c("43","47"))
  
  gearMap <- list()
  gearMap$Gillnet <- "GNS_DEF_all_0_0_all"
  gearMap$Trawl <- "OTB_DEF_>=120_0_0_all"
  
  areaMap <- list()
  areaTypeMap <- list()
  areaMap$a27.4 <- "27.4"
  areaTypeMap$a27.4 <- "SubArea"
  areaMap$a27.3.a.20 <- "27.3.a.20"
  areaTypeMap$a27.3.a.20 <- "SubDiv"
  areaMap$a27.7.d <- "27.7.d"
  areaTypeMap$a27.7.d <- "Div"
  areaMap$a27.6.a <- "27.6.a"
  areaTypeMap$a27.6.a <- "Div"
  
  #
  # Make Rstox reports
  #
  Rstox:::saveDecomposedCatchMatrix(stoxProjectname, catchAtAgeReportFileName, addQuarterToDecomp = F, plusgr=15, customMainAreaGrouping = stoxReportArea, decomposition = c("metier", "quarter"), unit = unitReports)
  Rstox:::saveDecomposedAgeGroupParameters(stoxProjectname, meanWeightReportFileName, addQuarterToDecomp = F, plusgr=15, customMainAreaGrouping = stoxReportArea, decomposition = c("metier", "quarter"))
  
  
  convertToSdLines(catchAtAgeReportFileName, meanWeightReportFileName, SDlinesFilename, gearMap, areaMap, areaTypeMap, speciesIntercatch, catchAtAgeUnit=unitInterCatch, landings=land) 
  
}


#
# set species name and stox project, so they match
# must be configured for each project
#
stoxProjectname = "~/workspace/stox/ECA_prosjekter/NSSK/ECA_NSSK_torsk_2019/"
speciesIntercatch = "COD"


caaReport <- paste("caaReport_", speciesIntercatch, ".csv", sep="")
meanWeightReport <- paste("meanWeightReport_", speciesIntercatch, ".csv", sep="")
SDlines <- paste("intercatch_", speciesIntercatch, ".csv", sep="")
runProjectsAndMakeReportsGilnetTrawl(stoxProjectname, speciesIntercatch, SDlines, caaReport, meanWeightReport)


